In [ ]:
"""Objective

Convert the cleaned dataset into a machine-learning-ready dataset by:

Handling categorical features
Creating meaningful new features
Scaling numerical features
Saving preprocessing artifacts
Exporting the final engineered dataset"""

In [ ]:
"""Cleaned Dataset
        │
        ▼
Load Dataset
        │
        ▼
Separate Numerical & Categorical Features
        │
        ▼
Feature Engineering
        │
        ▼
Encoding
        │
        ▼
Scaling
        │
        ▼
Final Dataset
        │
        ▼
Save Encoder
Save Scaler
Save Feature Names
Save Engineered Dataset"""

In [ ]:
"""04_Feature_Engineering.ipynb

1. Project Title
2. Import Libraries
3. Load Cleaned Dataset
4. Create Backup
5. Separate Feature Types
6. Create New Features
7. Encode Categorical Features
8. Scale Numerical Features
9. Validate Dataset
10. Save Scaler
11. Save Encoder
12. Save Feature Names
13. Save Engineered Dataset
14. Summary"""

In [ ]:
"""# ⚙️ Credit Risk Prediction System

# 04 - Feature Engineering

---

## Objective

This notebook prepares the cleaned dataset for machine learning by:

- Creating new informative features
- Encoding categorical variables
- Scaling numerical variables
- Saving preprocessing objects"""

In [14]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from pathlib import Path

import joblib

from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler,
    LabelEncoder
)

from sklearn.compose import ColumnTransformer

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [15]:
# ==========================================================
# Load Cleaned Dataset
# ==========================================================

DATA_PATH = "../data/processed/cleaned_credit_data.csv"

df = pd.read_csv(DATA_PATH)

print(df.shape)

df.head()

(1000, 11)

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,No Account,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,No Account,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad

In [16]:
# ==========================================================
# Dataset Information
# ==========================================================

print(df.info())

print()

print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1000 non-null   int64
 1   Age               1000 non-null   int64
 2   Sex               1000 non-null   object
 3   Job               1000 non-null   int64
 4   Housing           1000 non-null   object
 5   Saving accounts   1000 non-null   object
 6   Checking account  1000 non-null   object
 7   Credit amount     1000 non-null   int64
 8   Duration          1000 non-null   int64
 9   Purpose           1000 non-null   object
 10  Risk              1000 non-null   object
dtypes: int64(5), object(6)
memory usage: 86.1+ KB
None

Unnamed: 0          0
Age                 0
Sex                 0
Job                 0
Housing             0
Saving accounts     0
Checking account    0
Credit amount       0
Duration            0
Purpose             0
Risk                0
dtype: int64

In [17]:
# ==========================================================
# Backup Copy
# ==========================================================

feature_df = df.copy()

print("Backup Created")

Backup Created

In [18]:
# ==========================================================
# Features & Target
# ==========================================================

X = feature_df.drop("Risk", axis=1)

y = feature_df["Risk"]

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (1000, 10)
Target Shape : (1000,)

In [19]:
# ==========================================================
# Create Engineered Features
# ==========================================================

X["Credit_Per_Month"] = (
    X["Credit amount"] /
    X["Duration"]
)

X["Credit_Age_Ratio"] = (
    X["Credit amount"] /
    X["Age"]
)

X["Age_Duration_Product"] = (
    X["Age"] *
    X["Duration"]
)

X["Credit_Age_Product"] = (
    X["Credit amount"] *
    X["Age"]
)

X["Log_Credit_Amount"] = np.log1p(
    X["Credit amount"]
)

X["Log_Duration"] = np.log1p(
    X["Duration"]
)

X.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Credit_Per_Month,Credit_Age_Ratio,Age_Duration_Product,Credit_Age_Product,Log_Credit_Amount,Log_Duration
0,0,67,male,2,own,No Account,little,1169,6,radio/TV,194.833333,17.447761,402,78323,7.064759,1.945910
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,123.979167,270.500000,1056,130922,8.691483,3.891820
2,2,49,male,1,own,little,No Account,2096,12,education,174.666667,42.775510,588,102704,7.648263,2.564949
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,187.666667,175.155556,1890,354690,8.972464,3.761200
4,4,53,male,2,free,little,little,4870,24,car,202.916667,91.886792,1272,258110,8.491055,3.218876

In [20]:
# ==========================================================
# Numerical & Categorical Features
# ==========================================================

numerical_features = X.select_dtypes(
    include=["int64","float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include="object"
).columns.tolist()

print("Numerical Features")
print(numerical_features)

print()

print("Categorical Features")
print(categorical_features)

Numerical Features
['Unnamed: 0', 'Age', 'Job', 'Credit amount', 'Duration', 'Credit_Per_Month', 'Credit_Age_Ratio', 'Age_Duration_Product', 'Credit_Age_Product', 'Log_Credit_Amount', 'Log_Duration']

Categorical Features
['Sex', 'Housing', 'Saving accounts', 'Checking account', 'Purpose']

In [21]:
# ==========================================================
# Column Transformer
# ==========================================================

preprocessor = ColumnTransformer(

    transformers=[

        (

            "num",

            StandardScaler(),

            numerical_features

        ),

        (

            "cat",

            OneHotEncoder(

                handle_unknown="ignore",

                sparse_output=False

            ),

            categorical_features

        )

    ],

    remainder="drop"

)

print("Preprocessor Created Successfully")

Preprocessor Created Successfully

In [ ]:
"""Why this is better:

Automatically scales only numeric columns.
Automatically encodes only categorical columns.
Handles unseen categories during prediction.
Keeps preprocessing consistent."""

In [22]:
# ==========================================================
# Transform Dataset
# ==========================================================

X_processed = preprocessor.fit_transform(X)

print(X_processed.shape)

(1000, 33)

In [23]:
# ==========================================================
# Feature Names
# ==========================================================

feature_names = preprocessor.get_feature_names_out()

X_processed = pd.DataFrame(

    X_processed,

    columns=feature_names

)

X_processed.head()

,num__Unnamed: 0,num__Age,num__Job,num__Credit amount,num__Duration,num__Credit_Per_Month,num__Credit_Age_Ratio,num__Age_Duration_Product,num__Credit_Age_Product,num__Log_Credit_Amount,...,cat__Checking account_moderate,cat__Checking account_rich,cat__Purpose_business,cat__Purpose_car,cat__Purpose_domestic appliances,cat__Purpose_education,cat__Purpose_furniture/equipment,cat__Purpose_radio/TV,cat__Purpose_repairs,cat__Purpose_vacation/others
0,-1.730320,2.766456,0.146949,-0.745131,-1.236478,0.176948,-0.899591,-0.669863,-0.334336,-0.933992,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,-1.726856,-1.191404,0.146949,0.949817,2.248194,-0.284901,1.874923,0.633721,0.116504,1.163149,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,-1.723391,1.183312,-1.383771,-0.416562,-0.738668,0.045495,-0.621893,-0.299119,-0.125360,-0.181750,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,-1.719927,0.831502,0.146949,1.634247,1.750384,0.130233,0.829548,2.296089,2.034481,1.525385,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,-1.716463,1.535122,0.146949,0.566664,0.256953,0.229637,-0.083427,1.064262,1.206668,0.904761,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
# ==========================================================
# Encode Target
# ==========================================================

target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)

print(target_encoder.classes_)

['bad' 'good']

In [ ]:
# ==========================================================
# Save Preprocessor
# ==========================================================

MODELS = Path("../models")

MODELS.mkdir(exist_ok=True)

joblib.dump(

    preprocessor,

    MODELS / "preprocessor.pkl"

)

print("Preprocessor Saved")

Preprocessor Saved

In [26]:
joblib.dump(

    target_encoder,

    MODELS / "target_encoder.pkl"

)

print("Target Encoder Saved")

Target Encoder Saved

In [27]:
joblib.dump(

    feature_names,

    MODELS / "feature_columns.pkl"

)

print("Feature Names Saved")

Feature Names Saved

In [28]:
# ==========================================================
# Save Engineered Dataset
# ==========================================================

engineered = X_processed.copy()

engineered["Risk"] = y

engineered.to_csv(

    "../data/processed/engineered_credit_data.csv",

    index=False

)

print("Engineered Dataset Saved Successfully")

Engineered Dataset Saved Successfully